apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: froghanabiiii/node-app:v2
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"